### Importing

In [112]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Previews Data

In [113]:
df = pd.read_csv('../../data/results/Clean_Datafull_Train.csv', sep=',')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30891 entries, 0 to 30890
Data columns (total 37 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   3x      30891 non-null  float64
 1   3y      30891 non-null  float64
 2   4x      30891 non-null  float64
 3   4y      30891 non-null  float64
 4   5x      30891 non-null  float64
 5   5y      30891 non-null  float64
 6   6x      30891 non-null  float64
 7   6y      30891 non-null  float64
 8   7x      30891 non-null  float64
 9   7y      30891 non-null  float64
 10  8x      30891 non-null  float64
 11  8y      30891 non-null  float64
 12  9x      30891 non-null  float64
 13  9y      30891 non-null  float64
 14  10x     30891 non-null  float64
 15  10y     30891 non-null  float64
 16  11x     30891 non-null  float64
 17  11y     30891 non-null  float64
 18  12x     30891 non-null  float64
 19  12y     30891 non-null  float64
 20  13x     30891 non-null  float64
 21  13y     30891 non-null  float64
 22  14x     30891 non-null  float64
 23  14y     30891 non-null  float64
 24  15x     30891 non-null  float64
 25  15y     30891 non-null  float64
 26  16x     30891 non-null  float64
 27  16y     30891 non-null  float64
 28  17x     30891 non-null  float64
 29  17y     30891 non-null  float64
 30  18x     30891 non-null  float64
 31  18y     30891 non-null  float64
 32  19x     30891 non-null  float64
 33  19y     30891 non-null  float64
 34  20x     30891 non-null  float64
 35  20y     30891 non-null  float64
 36  char    30891 non-null  int64
dtypes: float64(36), int64(1)
memory usage: 8.7 MB

In [114]:
df.head()

,3x,3y,4x,4y,5x,5y,6x,6y,7x,7y,...,16y,17x,17y,18x,18y,19x,19y,20x,20y,char
0,262.374,354.810,248.102,248.011,360.925,374.588,373.911,243.114,369.098,328.899,...,471.021,587.605,425.540,598.047,337.165,559.660,410.858,548.164,455.238,0
1,243.082,361.876,239.491,259.676,343.380,363.937,354.870,244.351,358.127,343.693,...,476.613,560.803,418.030,567.584,346.090,533.656,416.844,524.283,450.811,0
2,244.345,356.561,243.655,256.638,354.901,367.226,360.576,246.427,360.391,346.481,...,473.187,573.173,418.568,580.205,339.026,541.187,411.295,528.062,445.777,0
3,254.365,357.569,231.482,241.993,345.978,381.637,359.122,239.129,353.375,323.262,...,463.566,577.341,425.073,581.486,337.553,551.375,410.228,546.574,449.936,0
4,253.082,378.250,236.840,269.307,363.884,381.668,368.143,253.612,366.595,342.386,...,474.730,579.387,435.620,580.810,350.078,548.222,420.887,539.430,455.738,0

## Splitting data<br>
Pisahkan data training dan testing pada datasets train

In [115]:
def train_test_split(X: pd.DataFrame, y: pd.DataFrame, test_size: float = 0.2, random_state:int = None):
    if random_state:
        np.random.seed(random_state)
    
    n_samples = len(X)                                                  # Total sampel
    shuffle_indices = np.random.permutation(np.arange(n_samples))       # Buat index sepanjang total sampel dan shuffle
  
    # Hitung ukuran besaran train dan test
    test_size = round(test_size * n_samples)
    train_size = n_samples - test_size
    
    # Masukkan kedalam index yang sudah di acak berdasarkan train dan test index
    train_indices = shuffle_indices[:train_size]
    test_indices = shuffle_indices[test_size:]
    
    # Pilih data berdasarkan index di atas
    X_train, X_test = X.iloc[train_indices], X.iloc[test_indices]
    y_train, y_test = y.iloc[train_indices], y.iloc[test_indices]
    
    return [X_train, X_test, y_train, y_test]

X = df.drop(columns=["char"])
y = df.char

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
X_train.head()

,3x,3y,4x,4y,5x,5y,6x,6y,7x,7y,...,16x,16y,17x,17y,18x,18y,19x,19y,20x,20y
16647,309.393,299.332,312.029,257.232,387.443,300.362,384.044,232.493,377.752,265.659,...,450.978,368.835,527.232,331.413,517.361,272.506,489.231,317.750,488.708,351.268
21996,387.083,281.258,405.381,233.078,394.222,329.344,405.483,248.008,414.128,204.261,...,456.951,344.448,512.032,358.147,535.355,293.712,506.716,315.892,480.105,350.661
1092,447.262,244.328,469.343,191.359,482.863,303.603,525.640,247.255,517.898,266.110,...,512.213,378.192,568.555,394.576,608.392,357.038,579.438,368.433,564.238,382.227
457,405.841,263.826,407.170,206.146,432.230,328.114,442.231,263.934,441.899,289.457,...,484.621,397.431,538.124,377.907,555.459,326.396,525.993,356.455,512.364,386.925
20843,504.628,308.034,550.672,308.964,539.200,313.138,603.786,257.056,644.091,222.889,...,513.806,362.316,572.529,410.486,599.227,370.065,565.543,359.503,529.176,364.367

## Scaler data train<br>

### Min-Max Scaler<br>
$$
S(X) = \frac{X - X_{min}}{X_{max} - X_{min}}
$$

In [116]:
def min_max_scaler(X: pd.DataFrame):
    return ((X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0)))

X_train_mm_scaler = min_max_scaler(X_train)
X_test_mm_scaler = min_max_scaler(X_test)

X_train_mm_scaler.head()

,3x,3y,4x,4y,5x,5y,6x,6y,7x,7y,...,16x,16y,17x,17y,18x,18y,19x,19y,20x,20y
16647,0.416787,0.423556,0.413973,0.355381,0.502927,0.477050,0.492116,0.333050,0.499173,0.360254,...,0.519674,0.350538,0.550853,0.229287,0.556041,0.162116,0.533840,0.215581,0.536004,0.491026
21996,0.502687,0.397981,0.508687,0.322011,0.509981,0.523080,0.512087,0.355275,0.531892,0.276994,...,0.524927,0.325329,0.536324,0.260238,0.572692,0.186637,0.549889,0.213435,0.528153,0.489733
1092,0.569226,0.345725,0.573582,0.264373,0.602214,0.482197,0.624012,0.354196,0.625228,0.360866,...,0.573529,0.360210,0.590352,0.302413,0.640279,0.259862,0.616635,0.274100,0.604935,0.556966
457,0.523428,0.373315,0.510502,0.284802,0.549529,0.521127,0.546317,0.378089,0.556870,0.392526,...,0.549262,0.380097,0.561264,0.283115,0.591296,0.224430,0.567582,0.260270,0.557593,0.566972
20843,0.632654,0.435869,0.656098,0.426851,0.660833,0.497341,0.696804,0.368237,0.738732,0.302255,...,0.574930,0.343799,0.594151,0.320833,0.631798,0.274925,0.603882,0.263790,0.572937,0.518925

### Standard Scaler<br>
$$
S(X) = \frac{X - \bar{X}}{\sigma}
$$

In [117]:
def std_scaler(X: pd.DataFrame):
    return ((X - X.mean(axis=0)) / X.std(axis=0))

X_train_std_scaler = std_scaler(X_train)
X_test_std_scaler = std_scaler(X_test)

X_train_std_scaler.head()

,3x,3y,4x,4y,5x,5y,6x,6y,7x,7y,...,16x,16y,17x,17y,18x,18y,19x,19y,20x,20y
16647,-1.241773,-0.659210,-1.130153,-0.714694,-0.998550,-0.733967,-0.936521,-0.608013,-0.894564,-0.019010,...,-0.449224,0.192872,0.083378,-0.752895,-0.210021,-0.876254,-0.381250,-0.331916,-0.283701,-0.006403
21996,-0.484570,-0.895021,-0.369351,-0.976525,-0.906005,-0.227263,-0.725113,-0.422478,-0.586538,-0.639786,...,-0.391593,-0.053518,-0.144850,-0.337881,-0.007073,-0.606601,-0.196482,-0.354436,-0.371220,-0.013156
1092,0.101963,-1.376846,0.151928,-1.428762,0.304093,-0.677303,0.459740,-0.431483,0.292168,-0.014450,...,0.141609,0.287409,0.703843,0.227636,0.816684,0.198644,0.571989,0.282399,0.484678,0.338052
457,-0.301745,-1.122456,-0.354771,-1.268470,-0.387132,-0.248767,-0.362746,-0.232029,-0.351378,0.221604,...,-0.124616,0.481787,0.246922,-0.031131,0.219672,-0.190996,0.007223,0.137217,-0.043044,0.390322
20843,0.661080,-0.545675,0.814745,-0.153915,1.073187,-0.510599,1.230329,-0.314279,1.360748,-0.451444,...,0.156979,0.127008,0.763513,0.474620,0.713315,0.364294,0.425157,0.174161,0.127987,0.139339

### Principal Components Analysis (PCA)

In [118]:
def pca(X: pd.DataFrame, n_components: int):
    x_centered = X - X.mean()                                       # Standarisasi Data
    cov_matrix = np.cov(x_centered, rowvar=False)                   # Pilih variasi matrix dari datasets
    eigenvalues, eigenmatrix = np.linalg.eigh(cov_matrix)           # Nilai eigenvalues dari variasi matrix
    
    sorted_eigenvalues = np.argsort(eigenvalues)[::-1]              # Sorting nilai eigenvalues dari terbesar ke terkecil
    sorted_eigenmatrix = eigenmatrix[:, sorted_eigenvalues]         # Sorting nilai eigenmatrix berdasarkan eigenvalues
    
    principal_components = sorted_eigenmatrix[:, :n_components]     # Pilih eigenmatrix yg sudah di sort berdasarkan n_components
    
    X_pca = np.dot(x_centered, principal_components)                # Kali silang matrix
    return pd.DataFrame(X_pca)

X_train_pca = pca(X_train, n_components=3)
X_test_pca = pca(X_test, n_components=3)

X_train_pca.head(10)

            0           1           2
0  314.017961   66.334555  -95.542141
1  242.548687  -54.000074  -71.770332
2 -106.744740  -83.392792 -130.553859
3   72.201351   62.199812 -109.006241
4 -344.863130 -261.286587    1.644969
5  226.457058 -267.128157    8.780826
6  109.930362  -31.846233   43.279426
7   18.086130 -101.246224 -109.884500
8  162.433685 -131.395255  -41.235123
9   90.378866   77.749843 -140.066425

## Build KNN models

In [119]:
class KNN:
    def __init__(self, k: int, p: int, weight, voting:str = "default"):
        self.k = k              # Nilai K untuk mencangkup NN
        self.p = p              # Nilai P untuk tipe distance
        self.weight = weight    # weight untuk tipe pembobotan
        self.voting = voting    # voting untuk jenis voting
    
    def fit(self, X_train: pd.DataFrame, y_train: pd.DataFrame):
        # Set nilai train & testing
        self.X_train = X_train.to_numpy()
        self.y_train = y_train.to_numpy()
        
    def _minkowski_distance(self, a, b):
        # Minkowski distance karena generalisasi dari Euclidean(2) dan Manhattan(1) distance
        return np.power(np.sum(np.abs(a - b) ** self.p, axis=1), 1 / self.p)
    
    def _get_nn(self, X_test: pd.DataFrame):
        distance = self._minkowski_distance(X_test, self.X_train)       # Hitung semua jarak test dengan train
        k_idxs = np.argsort(distance)[: self.k]                         # Urutkan dan cangkup class label berdasarkan K
        k_labels = [self.y_train[i] for i in k_idxs]                    # class-class label
        k_distance = [distance[i] for i in k_idxs]                      # dapatkan kembali distance namun sudah urut
        
        if self.weight == "uniform":                                    # Voting saja
            # Hitung berapa banyak jumlah kandidat dan lakukan voting
            values, counts = np.unique(k_labels, return_counts=True)
            max_count = max(counts)
            candidates = values[counts == max_count]
            
            if self.voting == "default":
                if len(candidates) > 1:
                    return np.random.choice(candidates)
                else:
                    return candidates[0]
            elif self.voting == "sort":
                if len(candidates) > 1:
                    return np.random.choice(candidates)
                else:
                    return sorted(candidates)[0]
            else:
                raise ValueError("\"voting\" argument doesn't match in options!")
        
        
        
        elif self.weight == "distance":                                 # Hitung pembobotan dan voting
            weights = [(1 / (d + 1e-5)) for d in k_distance]
        
        elif callable(self.weight):                                     # Custom distance
            weights = [self.weight(d) for d in k_distance]
        
        else:
            raise ValueError("\"voting\" argument doesn't match in options!")
        
        # Hitung berapa banyak jumlah kandidat berdasarkan bobot dan lakukan voting
        label_weights = dict()
        for label, weight in zip(k_labels, weights):
            label_weights[label] = label_weights.get(label, 0) + weight
        
        max_weight = max(label_weights.values())
        candidates = [label for label, weight in label_weights.items() if weight == max_weight]
        
        if self.voting == "default":
            if len(candidates) > 1:
                return np.random.choice(candidates)
            else:
                return candidates[0]
        elif self.voting == "sort":
            if len(candidates) > 1:
                return np.random.choice(candidates)
            else:
                return sorted(candidates)[0]
        else:
            raise ValueError("\"voting\" argument doesn't match in options!")
        
    def predict(self, X_test: pd.DataFrame):
        return np.array([
            self._get_nn(x)
            for x in X_test.to_numpy()
        ])

## Evaluation Model

In [120]:
class EvaluationModel:
    def __init__(self, y_true: pd.DataFrame, y_pred: np.ndarray):
        self.y_true = y_true # Data dari datasets
        self.y_pred = y_pred # Data dari hasil prediksi model
    
    def accuracy(self):
        return np.sum(self.y_true == self.y_pred) / len(self.y_true)
    
    def precision(self, TP, FP):
        return TP / (TP + FP) if (TP + FP) != 0 else 0
    
    def recall(self, TP, FN):
        return TP / (TP + FN) if (TP + FN) != 0 else 0
    
    def f1_score(self, TP, FP, FN):
        P = self.precision(TP, FP)
        R = self.recall(TP, FN)
        
        return 2 * (P * R) / (P + R) if (P + R) != 0 else 0
    
    def macro_avg(self, report_df: pd.DataFrame):
        return report_df[["Precision", "Recall", "F1-Score"]].mean()
    
    def weighted_avg(self, report_df: pd.DataFrame):
        class_vc = self.y_true.value_counts()
        total_samples = len(self.y_true)
        
        weighted_dict = dict()
        for col in ["Precision", "Recall", "F1-Score"]:
            weighted_sum = 0
            for i, row in report_df.iterrows():
                if row["Category"] not in ["macro avg", "weighted avg"]:
                    cat = row["Category"]
                    cat_weight = class_vc.get(cat, 0) / total_samples
                    weighted_sum += cat_weight * row[col]
            
            weighted_dict[col] = weighted_sum
        
        return weighted_dict
    
    def make_report(self):
        cats = pd.Series(self.y_true).unique()
        report_dict = {"Category": [], "Precision": [], "Recall": [], "F1-Score": []}
        
        for cat in cats:
            # Confusion matrixs
            TP = np.sum((self.y_true == cat) & (self.y_pred == cat)) # Asli POSITIF prdiksi POSITIF
            TN = np.sum((self.y_true != cat) & (self.y_pred != cat)) # Asli NEGATIF prdiksi NEGATIF
            FP = np.sum((self.y_true != cat) & (self.y_pred == cat)) # Asli NEGATIF prdiksi POSITIF
            FN = np.sum((self.y_true == cat) & (self.y_pred != cat)) # Asli POSITIF prdiksi NEGATIF
            
            # Calculation matrixs
            P = self.precision(TP, FP)
            R = self.recall(TP, FN)
            F1 = self.f1_score(TP, FP, FN)
            
            # Append matrixs
            report_dict["Category"].append(cat)
            report_dict["Precision"].append(P)
            report_dict["Recall"].append(R)
            report_dict["F1-Score"].append(F1)
        
        accuracy = self.accuracy()
        
        report_df = pd.DataFrame(report_dict)
        macro_avg = self.macro_avg(report_df)
        weighted_avg = self.weighted_avg(report_df)
        
        summary_df = pd.DataFrame.from_records([
            {"Category": "macro avg", **macro_avg},
            {"Category": "weighted avg", **weighted_avg}
        ])
        
        result_df = pd.concat([report_df, summary_df], ignore_index=True)
        
        return result_df, accuracy

## Implements model with clean training datasets

In [121]:
def custom_distance(d):
    return (1 / (d**2 + 1e-5))

model_final = KNN(k=3, p=3, weight=custom_distance, voting="default")
model_final.fit(X_train=X_train, y_train=y_train)

preds = model_final.predict(X_test=X_test)

# Evaluation
eval_model = EvaluationModel(y_true=y_test, y_pred=preds)
report_df, accuracy = eval_model.make_report()

print(f"Accuracy model final: {accuracy*100:.2f}%")
report_df

Accuracy model final: 98.05%

        Category  Precision    Recall  F1-Score
0              7   0.994480  0.998153  0.996313
1             22   0.956483  0.972900  0.964622
2             15   0.992188  0.986408  0.989289
3             16   0.987542  0.985904  0.986722
4              4   0.970615  0.984171  0.977346
5              0   0.985089  0.984171  0.984630
6              3   0.972275  0.968571  0.970420
7              6   0.981783  0.979904  0.980843
8             17   0.962209  0.957570  0.959884
9             13   0.980170  0.979245  0.979707
10            19   0.982358  0.983271  0.982815
11             8   0.976818  0.958635  0.967641
12             9   0.986248  0.977605  0.981907
13            12   0.967243  0.964610  0.965925
14            23   0.997217  0.989871  0.993530
15             2   0.978907  0.973308  0.976099
16             5   0.988690  0.986830  0.987759
17             1   0.982524  0.991185  0.986836
18            18   0.967332  0.977085  0.972184
19            11   0.962477  0.969754  0.966102
20            14   0.987768  0.990798  0.989280
21            20   0.992773  0.993671  0.993222
22            21   0.993772  0.988496  0.991127
23            10   0.994197  0.994197  0.994197
24     macro avg   0.980882  0.980680  0.980767
25  weighted avg   0.980573  0.980537  0.980541

## Implements model with clean testing datasets

### Import data

In [ ]:
df_test = pd.read_csv("../../data/results/Clean_DataFull_Terakhir_Test.csv")

X_test_val = df_test.drop(columns=["char"])
y_test_val = df_test.char

### Use model

In [123]:
preds_final = model_final.predict(X_test=X_test_val)

# Evaluation
eval_model = EvaluationModel(y_true=y_test_val, y_pred=preds_final)
report_df, accuracy = eval_model.make_report()

print(f"Accuracy model final: {accuracy*100:.2f}%")
report_df

Accuracy model final: 91.92%

        Category  Precision    Recall  F1-Score
0              0   0.925697  0.917178  0.921418
1              1   0.944785  0.965517  0.955039
2              2   0.887240  0.908815  0.897898
3              3   0.928105  0.858006  0.891680
4              4   0.882521  0.916667  0.899270
5              5   0.966667  0.957958  0.962293
6              6   0.902439  0.902439  0.902439
7              7   0.968116  0.985251  0.976608
8              8   0.900685  0.865132  0.882550
9              9   0.936909  0.905488  0.920930
10            10   0.955490  0.978723  0.966967
11            11   0.850144  0.893939  0.871492
12            12   0.870871  0.857988  0.864382
13            13   0.911585  0.920000  0.915773
14            14   0.972350  0.963470  0.967890
15            15   0.987654  0.941176  0.963855
16            16   0.921622  0.924119  0.922869
17            17   0.851064  0.858896  0.854962
18            18   0.882184  0.910979  0.896350
19            19   0.897436  0.926471  0.911722
20            20   0.973607  0.945869  0.959538
21            21   0.988166  0.957020  0.972344
22            22   0.847222  0.884058  0.865248
23            23   0.969880  0.933333  0.951256
24     macro avg   0.921768  0.919937  0.920615
25  weighted avg   0.919936  0.919184  0.919327

#### I think model is overfitting or the datasets is so good

## Try to manual predict

In [ ]:
df_test[df_test["char"] == 19].tail()

,3x,3y,4x,4y,5x,5y,6x,6y,7x,7y,...,16y,17x,17y,18x,18y,19x,19y,20x,20y,char
6351,417.927,329.612,445.609,311.176,411.955,320.928,414.468,250.992,413.523,207.315,...,374.048,515.215,365.065,525.357,320.178,504.378,345.902,485.534,376.663,19
6352,417.497,324.821,438.547,304.803,423.164,320.263,429.261,251.302,430.014,206.816,...,384.148,525.285,364.293,532.929,323.556,508.554,349.841,487.905,381.322,19
6353,429.359,303.604,451.511,280.451,428.918,310.860,436.438,234.860,438.641,190.210,...,374.055,529.165,358.837,539.758,317.298,516.420,346.123,498.733,378.189,19
6354,417.430,310.153,436.532,286.587,426.046,315.447,430.828,240.762,434.458,195.891,...,370.978,529.372,361.404,540.249,316.651,518.108,344.549,497.710,375.952,19
6355,416.689,313.621,441.608,289.915,419.134,313.454,425.139,239.132,429.157,195.444,...,374.384,521.782,363.324,535.542,320.502,513.539,349.090,494.515,378.430,19

In [125]:
struct = {0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E', 5: 'F', 6: 'G', 7: 'H', 8: 'I', 9: 'K', 10: 'L', 11: 'M', 12: 'N', 13: 'O', 14: 'P', 15: 'Q', 16: 'R', 17: 'S', 18: 'T', 19: 'U', 20: 'V', 21: 'W', 22: 'X', 23: 'Y'}

In [183]:
struct[23]

'Y'

In [181]:
from IPython.display import display

data_df = df_test.iloc[[6352]].drop(columns=["char"])
display(data_df)

# Prediksi
test_predict = model_final.predict(data_df)

print(f"Model Predict: {test_predict}")
print(f"Actual: {struct[int(test_predict)]}")

,3x,3y,4x,4y,5x,5y,6x,6y,7x,7y,...,16x,16y,17x,17y,18x,18y,19x,19y,20x,20y
6352,417.497,324.821,438.547,304.803,423.164,320.263,429.261,251.302,430.014,206.816,...,469.936,384.148,525.285,364.293,532.929,323.556,508.554,349.841,487.905,381.322

Model Predict: [19]
Actual: U

C:\Users\Admin\AppData\Local\Temp\ipykernel_9888\4246067639.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(f"Actual: {struct[int(test_predict)]}")